### ISSUE TITLE
As per the instruction install but not solved ingress.

### ISSUE THREAD

**Issue by devopsdymyr** [PacktPublishing/Hands-On-Kubernetes-on-Azure#4] opened 2019-08-11 17:26 UTC
As per the instruction install but not solved ingress.
![Screenshot from 2019-08-11 22-48-15](https://user-images.githubusercontent.com/41105507/62837235-fbf29a80-bc8a-11e9-9231-4acbfbe07ec0.png)
![Screenshot from 2019-08-11 22-49-11](https://user-images.githubusercontent.com/41105507/62837241-090f8980-bc8b-11e9-9f42-48092668ef7e.png)
![Screenshot from 2019-08-11 22-50-41](https://user-images.githubusercontent.com/41105507/62837244-0c0a7a00-bc8b-11e9-8d4a-729d089caf6f.png)
![Screenshot from 2019-08-11 22-52-39](https://user-images.githubusercontent.com/41105507/62837245-0f056a80-bc8b-11e9-9132-8d1ed88069d2.png)

I am trying with as per steps provided in the book.let me know anything required to change in the chapter 5

_Originally posted by @devopsdymyr in https://github.com/PacktPublishing/Hands-On-Kubernetes-on-Azure/issues/2#issuecomment-520245640_

**Comment by gshiva** [comment] 2019-08-11 22:33
Looks like the command itself worked. There might be some network issue. Also it takes some time to ingress to start running.

It would be helpful to know why exactly the pod is restarting. Try 

```bash
kubectl logs <ingress-pod-name>
```

**Comment by gshiva** [comment] 2019-08-12 00:18
Can you also try this?

** the following doesn't set the rbac.create =false flag **

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
helm install stable/nginx-ingress
```

#2 - might also need this update.

**Comment by gshiva** [comment] 2019-08-12 00:46
Closing this as duplicate of #2

**Closed as completed by gshiva** 2019-08-12 00:46 UTC
